/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastros.Livraria;

import Cadastros.classes.autores;
import Cadastros.classes.editoras;
import Cadastros.classes.livros;
import Cadastros.pastaDAO.autoresDAO;
import Cadastros.pastaDAO.editorasDAO;
import Cadastros.pastaDAO.livrosDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davy.scheuermann
 */
public class FormLivros extends javax.swing.JFrame {

    public FormLivros() {
        initComponents();
        this.setLocationRelativeTo(null);
        carregaDados();

        editorasDAO eDAO = new editorasDAO();
        autoresDAO aDAO = new autoresDAO();
        for (editoras e : eDAO.listar()) {
            CB_Editoras.addItem(e);
        }
        for (autores a : aDAO.listar()) {
            CB_Autor.addItem(a);
        }
    }

    ;
    
    public void carregaDados() {
        DefaultTableModel tabela = (DefaultTableModel) TB_Livros.getModel();

        livrosDAO DAO = new livrosDAO();
        tabela.setNumRows(0);

        for (livros l : DAO.listar()) {
            tabela.addRow(new Object[]{
                l.getId_livro(),
                l.getTitulo(),
                l.getEditora(),
                l.getAutor(),
                l.getAno()
            });
        }
    }

    public void pesquisaDados() {
        DefaultTableModel tabela = (DefaultTableModel) TB_Livros.getModel();
        livrosDAO dao = new livrosDAO();
        tabela.setNumRows(0);

        for (livros l : dao.pesquisar(TF_Pesquisar.getText())) {
            tabela.addRow(new Object[]{
                l.getId_livro(),
                l.getTitulo(),
                l.getEditora(),
                l.getAutor(),
                l.getAno()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TF_Codigo = new javax.swing.JTextField();
        CB_Editoras = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CB_Autor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TF_Titulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_Ano = new javax.swing.JTextField();
        BTT_Cadastrar = new javax.swing.JButton();
        BTT_Alterar = new javax.swing.JButton();
        BTT_Excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Livros = new javax.swing.JTable();
        TF_Pesquisar = new javax.swing.JTextField();
        BTT_Pesquisar = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        CB_Editoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EditorasActionPerformed(evt);
            }
        });

        jLabel2.setText("Editora");

        jLabel3.setText("Autor");

        CB_Autor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CB_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_AutorActionPerformed(evt);
            }
        });

        jLabel4.setText("Título");

        TF_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TituloActionPerformed(evt);
            }
        });

        jLabel5.setText("Ano");

        TF_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AnoActionPerformed(evt);
            }
        });

        BTT_Cadastrar.setText("Cadastrar");
        BTT_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_CadastrarActionPerformed(evt);
            }
        });

        BTT_Alterar.setText("Alterar");
        BTT_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_AlterarActionPerformed(evt);
            }
        });

        BTT_Excluir.setText("Excluir");
        BTT_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_ExcluirActionPerformed(evt);
            }
        });

        TB_Livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Editora", "Autor", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_Livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_LivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TB_Livros);
        if (TB_Livros.getColumnModel().getColumnCount() > 0) {
            TB_Livros.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        TF_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PesquisarActionPerformed(evt);
            }
        });

        BTT_Pesquisar.setText("Pesquisar");
        BTT_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTT_Cadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTT_Alterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTT_Excluir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TF_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTT_Pesquisar))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TF_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_Editoras, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CB_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(TF_Titulo)))
                        .addGap(0, 483, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(TF_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CB_Editoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CB_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTT_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTT_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TituloActionPerformed

    private void TF_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AnoActionPerformed

    //*************************************************************************

    private void BTT_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_AlterarActionPerformed
        livros l = new livros();
        livrosDAO DAO = new livrosDAO();

        editoras editora = (editoras) CB_Editoras.getSelectedItem();
        autores autor = (autores) CB_Autor.getSelectedItem();

        l.setEditora(editora);
        l.setAutor(autor);
        l.setTitulo(TF_Titulo.getText());
        l.setAno(Integer.parseInt(TF_Ano.getText()));
        l.setId_livro(Integer.parseInt(TF_Codigo.getText()));
        DAO.alterar(l);
        carregaDados();
    }//GEN-LAST:event_BTT_AlterarActionPerformed

    private void TF_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PesquisarActionPerformed

    private void CB_EditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EditorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EditorasActionPerformed

    private void CB_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_AutorActionPerformed

    //*************************************************************************

    private void BTT_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_CadastrarActionPerformed

        livros l = new livros();
        livrosDAO DAO = new livrosDAO();

        editoras editora = (editoras) CB_Editoras.getSelectedItem();
        autores autor = (autores) CB_Autor.getSelectedItem();

        l.setEditora(editora);
        l.setAutor(autor);
        l.setTitulo(TF_Titulo.getText());
        l.setAno(Integer.parseInt(TF_Ano.getText()));

        DAO.cadastrar(l);
        carregaDados();
    }//GEN-LAST:event_BTT_CadastrarActionPerformed

    //*************************************************************************

    private void BTT_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_PesquisarActionPerformed
        pesquisaDados();
    }//GEN-LAST:event_BTT_PesquisarActionPerformed

    //*************************************************************************

    private void BTT_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_ExcluirActionPerformed
        livros l = new livros();
        livrosDAO DAO = new livrosDAO();

        l.setId_livro(Integer.parseInt(TF_Codigo.getText()));
        DAO.excluir(l);
        carregaDados();
    }//GEN-LAST:event_BTT_ExcluirActionPerformed

    //*************************************************************************

    private void TB_LivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_LivrosMouseClicked

     String comboAutor = TB_Livros.getValueAt(TB_Livros.getSelectedRow(), 3).toString();
        String comboEditora = TB_Livros.getValueAt(TB_Livros.getSelectedRow(), 2).toString();
        
        
        TF_Codigo.setText(TB_Livros.getValueAt(TB_Livros.getSelectedRow(), 0).toString());
        TF_Ano.setText(TB_Livros.getValueAt(TB_Livros.getSelectedRow(), 4).toString());
        TF_Titulo.setText(TB_Livros.getValueAt(TB_Livros.getSelectedRow(), 1).toString());

        
        for (int i = 0; i < CB_Editoras.getItemCount(); i++) {
            if (CB_Editoras.getItemAt(i).toString().equalsIgnoreCase(comboEditora)) {
                CB_Editoras.setSelectedIndex(i);
            }
        }

       
        for (int i = 0; i < CB_Autor.getItemCount(); i++) {
            if (CB_Autor.getItemAt(i).toString().equalsIgnoreCase(comboAutor)) {
                CB_Autor.setSelectedIndex(i);
            }
        }

    }//GEN-LAST:event_TB_LivrosMouseClicked
        
     
     
    //*************************************************************************
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTT_Alterar;
    private javax.swing.JButton BTT_Cadastrar;
    private javax.swing.JButton BTT_Excluir;
    private javax.swing.JButton BTT_Pesquisar;
    private javax.swing.JComboBox<Object> CB_Autor;
    private javax.swing.JComboBox<Object> CB_Editoras;
    private javax.swing.JTable TB_Livros;
    private javax.swing.JTextField TF_Ano;
    private javax.swing.JTextField TF_Codigo;
    private javax.swing.JTextField TF_Pesquisar;
    private javax.swing.JTextField TF_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
