/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastros.Livraria;

import Cadastros.classes.autores;
import Cadastros.pastaDAO.autoresDAO;
import java.math.BigInteger;

/**
 *
 * @author davy.scheuermann
 */
public class FormAutores extends javax.swing.JFrame {

    /**
     * Creates new form FormAutores
     */
    public FormAutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        LBL_id_Autor = new javax.swing.JLabel();
        TF_id_Autor = new javax.swing.JTextField();
        LBL_Nome = new javax.swing.JLabel();
        TF_Nome = new javax.swing.JTextField();
        LBL_Endereco = new javax.swing.JLabel();
        TF_Endereco = new javax.swing.JTextField();
        LBL_Numero = new javax.swing.JLabel();
        TF_Numero = new javax.swing.JTextField();
        LBL_Bairro = new javax.swing.JLabel();
        TF_Bairro = new javax.swing.JTextField();
        LBL_Cidade = new javax.swing.JLabel();
        TF_Cidade = new javax.swing.JTextField();
        LBL_CPF = new javax.swing.JLabel();
        TF_CPF = new javax.swing.JTextField();
        BTT_Cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autores"));

        LBL_id_Autor.setText("id Autor");
        LBL_id_Autor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        LBL_Nome.setText("Nome");

        TF_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NomeActionPerformed(evt);
            }
        });

        LBL_Endereco.setText("Endereco");

        TF_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EnderecoActionPerformed(evt);
            }
        });

        LBL_Numero.setText("Número");

        TF_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NumeroActionPerformed(evt);
            }
        });

        LBL_Bairro.setText("Bairro");

        TF_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_BairroActionPerformed(evt);
            }
        });

        LBL_Cidade.setText("Cidade");

        TF_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CidadeActionPerformed(evt);
            }
        });

        LBL_CPF.setText("CPF");

        BTT_Cadastrar.setText("Cadastrar");
        BTT_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_id_Autor)
                            .addComponent(LBL_Endereco)
                            .addComponent(LBL_Numero))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Endereco)
                            .addComponent(TF_Numero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_id_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_Bairro)
                            .addComponent(LBL_Cidade)
                            .addComponent(LBL_CPF))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Bairro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TF_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TF_Cidade))))
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBL_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(BTT_Cadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_id_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_id_Autor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Nome)
                    .addComponent(TF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Endereco)
                    .addComponent(TF_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Numero)
                    .addComponent(TF_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Bairro)
                    .addComponent(TF_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Cidade)
                    .addComponent(TF_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_CPF)
                    .addComponent(TF_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(BTT_Cadastrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NomeActionPerformed

    private void TF_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EnderecoActionPerformed

    private void TF_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NumeroActionPerformed

    private void TF_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_BairroActionPerformed

    private void TF_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CidadeActionPerformed

    private void BTT_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_CadastrarActionPerformed

        autores a = new autores();
        autoresDAO DAO = new autoresDAO();

        a.setNome(TF_Nome.getText());
        a.setEndereco(TF_Endereco.getText());
        a.setNumero(Integer.parseInt(TF_Numero.getText()));
        a.setBairro(TF_Bairro.getText());
        a.setCidade(TF_Cidade.getText());
        a.setCpf(new BigInteger(TF_CPF.getText()));
       
        DAO.cadastrar(a);
        
        /*TF_Bairro.setText("");
        TF_Endereco.setText("");
        TF_Numero.setText("");
        TF_Nome.setText("");
        TF_Cidade.setText("");
        TF_CPF.setText("");
        apenas quando o cadastro for verificado*/
        
    }//GEN-LAST:event_BTT_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAutores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTT_Cadastrar;
    private javax.swing.JLabel LBL_Bairro;
    private javax.swing.JLabel LBL_CPF;
    private javax.swing.JLabel LBL_Cidade;
    private javax.swing.JLabel LBL_Endereco;
    private javax.swing.JLabel LBL_Nome;
    private javax.swing.JLabel LBL_Numero;
    private javax.swing.JLabel LBL_id_Autor;
    private javax.swing.JTextField TF_Bairro;
    private javax.swing.JTextField TF_CPF;
    private javax.swing.JTextField TF_Cidade;
    private javax.swing.JTextField TF_Endereco;
    private javax.swing.JTextField TF_Nome;
    private javax.swing.JTextField TF_Numero;
    private javax.swing.JTextField TF_id_Autor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
